import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";


const nunito = Nunito({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Encontre seu amigo!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
